@startuml "Mars Rover Challenge"
skinparam classAttributeIconSize 0

interface IInstructionReader <<interface>>
{
  + EvaluateInstruction(instruction : string) : List<SingularInstruction>
  + IsValidInstruction(instruction : string) : bool
}

enum SingularInstruction
{
  TurnLeft
  TurnRight
  MoveForward
}

class StandardInstructionReader
{
  + EvaluateInstruction(instruction : string) : List<SingularInstruction>
  + IsValidInstruction(instruction : string) : bool
}

interface IPlateau <<interface>>
{
  + IsCoordinateValid(coordinates : Coordinates) : bool
}

class RectangularPlateau
{
  + maximumCoordinates : Coordinates
  + obstaclesCoordinates : List<Coordinates>

  + RectangularPlateau(maximumCoordinates : Coordinates, obstaclesCoordinates : List<Coordinates>)
  + RectangularPlateau(maximumCoordinates : Coordinates)

  + IsCoordinateValid(coordinates : Coordinates) : bool
}

class Coordinates
{
  + x : int
  + y : int

  + IsValidCoordinateString(input : string) : bool
  + ToCoordinates(input : string) : Coordinates
}

class Direction
{
  - directions : List<(char, Coordinates)>
  - directionIndex : int

  + GetChar() : char
  + GetCoordinates() : Coordinates
  + TurnLeft() : void
  + TurnRight() : void
}

interface IPositionStringConverter <<interface>>
{
  + IsValidPositionString(position : string) : bool
  + ToCoordinatesDirection(position : string) : (Coordinates, Direction)
  + ToPositionString(coordinates : Coordinates, direction : Direction) : string
}

class PositionStringConverter
{
  + IsValidPositionString(position : string) : bool
  + ToCoordinatesDirection(position : string) : (Coordinates, Direction)
  + ToPositionString(coordinates : Coordinates, direction : Direction) : string
}

abstract VehicleBase <<abstract>>
{
  - coordinates : Coordinates
  - direction : Direction
  - plateau : IPlateau
  - instructionReader : IInstructionReader
  - positionStringConverter : IPositionStringConverter

  + VehicleBase(initialPosition : string, plateau : IPlateau, positionStringConverter : IPositionStringConverter)
  + VehicleBase(initialPosition : string, plateau : IPlateau)

  + SwapInstructionReader(instructionReader : IInstructionReader) : void
  + SwapPositionStringConverter(positionStringConverter : IPositionStringConverter) : void
  
  + GetPosition() : string
  + ApplyMoveInstruction() : void
  + TeleportToPosition(position : string) : void
}

class Rover
{
  - remainingSampleStorageSpace : int

  + Rover(initialPosition : string, plateau : IPlateau, positionStringConverter : IPositionStringConverter)
  + Rover(initialPosition : string, plateau : IPlateau)

  + TakePhotoAndSendToStation() : void
  + CollectSample() : void
}

IInstructionReader -> SingularInstruction
IInstructionReader <|.. StandardInstructionReader 
IPlateau <|.. RectangularPlateau

IPositionStringConverter <|.. PositionStringConverter

VehicleBase <|-r- Rover

IPlateau --> Coordinates
Direction --> Coordinates
IPositionStringConverter --> Coordinates
IPositionStringConverter --> Direction

VehicleBase o-- Coordinates
VehicleBase o-- Direction
VehicleBase o--- IPlateau
VehicleBase o-l IInstructionReader
VehicleBase o-- IPositionStringConverter

VehicleBase --> SingularInstruction

@enduml