@startuml "Mars Rover Challenge"
skinparam classAttributeIconSize 0

class CommandHandler
{
  - instructionReader : IInstructionReader
  - positionStringConverter : IPositionStringConverter
  - vehicle : VehicleBase
  - RecentPath : List<&#40;Coordinates, Direction&#41;>

  + CommandHandler(instructionReader : IInstructionReader, positionStringConverter : IPositionStringConverter)
  
  + GetRecentPath() : List<(Coordinates, Direction)>

  + ConnectVehicle(vehicle : VehicleBase)
  + DisconnectVehicle()

  + RequestPosition() : string
  + SendMoveInstruction(instruction : string) : (bool, string)
}

interface IInstructionReader <<interface>>
{
  + IsValidInstruction(instruction : string) : bool
  + EvaluateInstruction(instruction : string) : List<SingularInstruction>
}

enum SingularInstruction
{
  TurnLeft
  TurnRight
  MoveForward
}

class StandardInstructionReader
{
  + IsValidInstruction(instruction : string) : bool
  + EvaluateInstruction(instruction : string) : List<SingularInstruction>
}

abstract PlateauBase <<abstract>>
{
  - obstacleCoordinates : List<Coordinates>

  + GetObstacleCoordinates() : List<Coordinates>
  + AddObstacle(obstacleCoordinate: Coordinates)
  + RemoveObstacle(obstacleCoordinate: Coordinates)
  {abstract} + IsCoordinateValidInPlateau(coordinates : Coordinates) : bool
  {abstract} + PrintMap(recentPath : List<(Coordinates, Direction)>) : void
}

class RectangularPlateau
{
  + plateauSize : Coordinates

  + RectangularPlateau(plateauSize : Coordinates)

  + IsCoordinateValidInPlateau(coordinates : Coordinates) : bool
  + PrintMap(recentPath : List<(Coordinates, Direction)>) : void
}

class Coordinates
{
  + x : int
  + y : int

  + operator+(a : Coordinates, b : Coordinates) : Coordinates
}

enum Direction
{
  North
  East
  South
  West

  + GetMovementVector() : Coordinates
  + GetLeftTurn() : Direction
  + GetRightTurn() : Direction
}

interface IPositionStringConverter <<interface>>
{
  + IsValidPositionString(position : string) : bool
  + IsValidCoordinateString(coordinateString : string) : bool

  + ToCoordinatesDirection(position : string) : (Coordinates, Direction)
  + ToCoordinates(coordinateString : string) : Coordinates

  + ToPositionString(coordinates : Coordinates, direction : Direction) : string
}

class PositionStringConverter
{
  + IsValidPositionString(position : string) : bool
  + IsValidCoordinateString(coordinateString : string) : bool

  + ToCoordinatesDirection(position : string) : (Coordinates, Direction)
  + ToCoordinates(coordinateString : string) : Coordinates

  + ToPositionString(coordinates : Coordinates, direction : Direction) : string
}

class Rover
{
  + Rover(initialCoordinates : Coordinates, initialDirection : Direction, plateau : PlateauBase)

  + TakePhotoAndSendToStation() : void
  + CollectSample() : void
}

abstract VehicleBase <<abstract>>
{
  - coordinates : Coordinates
  - direction : Direction
  - plateau : PlateauBase

  + VehicleBase(initialCoordinates : Coordinates, initialDirection : Direction, plateau : PlateauBase)

  + GetCoordinates() : Coordinates
  + GetDirection() : Direction
  + GetPlateau() : PlateauBase
  + ApplyMoveInstruction(instruction : List<SingularInstruction>) : void
}

CommandHandler o-- IInstructionReader
CommandHandler o-- IPositionStringConverter
CommandHandler o-- VehicleBase
CommandHandler -----> Coordinates
CommandHandler ----> Direction

IInstructionReader --> SingularInstruction
IInstructionReader <|.. StandardInstructionReader 

VehicleBase <|-u- Rover
VehicleBase --> SingularInstruction
VehicleBase o--- Direction
VehicleBase o---- Coordinates
VehicleBase o-- PlateauBase

IPositionStringConverter <|.. PositionStringConverter
IPositionStringConverter ---> Direction
IPositionStringConverter ----> Coordinates

PlateauBase <|-- RectangularPlateau
PlateauBase o--- Coordinates

Direction --> Coordinates 

@enduml